# docker-compose.yml
version: '3.8'

services:
  # A2A Server (default)
  clintrialsgpt-a2a:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RUN_MODE=a2a
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src/openai-api-key.txt:/app/src/openai-api-key.txt:ro

  # Original Streamlit App
  clintrialsgpt-streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - RUN_MODE=streamlit
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src/openai-api-key.txt:/app/src/openai-api-key.txt:ro